volumes:
  developerapp_local_postgres_data: {}
  developerapp_local_postgres_backups: {}
  developerapp_local_redis_data: {}

x-env-common: &common_env
  USE_DOCKER:
  IPYTHONDIR:
  REDIS_URL:
  CELERY_FLOWER_USER:
  CELERY_FLOWER_PASSWORD:
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:

x-django-base: &django_base
  build:
    context: .
    dockerfile: ./compose/local/django/Dockerfile
  volumes:
    - /app/.venv
    - .:/app:z
  environment:
    <<: *common_env
  depends_on:
    - postgres
    - redis
    - mailpit

services:

  django:
    <<: *django_base
    image: developerapp_local_django
    container_name: developerapp_local_django
    ports:
      - "8000:8000"
    command: /start


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: developerapp_local_postgres
    container_name: developerapp_local_postgres
    volumes:
      - developerapp_local_postgres_data:/var/lib/postgresql/18/docker
      - developerapp_local_postgres_backups:/backups
    environment:
      POSTGRES_HOST:
      POSTGRES_PORT:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:


  mailpit:
    image: axllent/mailpit:latest
    container_name: developerapp_local_mailpit
    ports:
      - "8025:8025"


  redis:
    image: redis:7.2
    container_name: developerapp_local_redis
    volumes:
      - developerapp_local_redis_data:/data


  celeryworker:
    <<: *django_base
    image: developerapp_local_celeryworker
    container_name: developerapp_local_celeryworker
    ports: []
    command: /start-celeryworker


  celerybeat:
    <<: *django_base
    image: developerapp_local_celerybeat
    container_name: developerapp_local_celerybeat
    ports: []
    command: /start-celerybeat


  flower:
    <<: *django_base
    image: developerapp_local_flower
    container_name: developerapp_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
