# ---------------------------------------------------------
# Volumes
# ---------------------------------------------------------
volumes:
  postgres_data: {}
  postgres_backups: {}
  redis_data: {}
  django_media: {}
  traefik_data: {}

# ---------------------------------------------------------
# Shared environment (provided by Doppler)
# ---------------------------------------------------------
x-common-env: &common_env
  DJANGO_SECRET_KEY:
  DJANGO_ALLOWED_HOSTS:
  DJANGO_DEBUG:
  DATABASE_URL:
  REDIS_URL:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_HOST:
  POSTGRES_PORT:
  CELERY_FLOWER_USER:
  CELERY_FLOWER_PASSWORD:

# ---------------------------------------------------------
# Django Base Template
# ---------------------------------------------------------
x-django-base: &django_base
  build:
    context: .
    dockerfile: ./compose/production/django/Dockerfile
  volumes:
    - django_media:/app/developerapp/media
  environment:
    <<: *common_env
  depends_on:
    - postgres
    - redis

# ---------------------------------------------------------
# Services
# ---------------------------------------------------------
services:

  django:
    <<: *django_base
    image: developerapp_production_django
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: developerapp_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
      - postgres_backups:/backups
    environment:
      <<: *common_env

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: developerapp_production_traefik
    depends_on:
      - django
    volumes:
      - traefik_data:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  celeryworker:
    <<: *django_base
    image: developerapp_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django_base
    image: developerapp_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django_base
    image: developerapp_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: developerapp_production_nginx
    depends_on:
      - django
    volumes:
      - django_media:/usr/share/nginx/media:ro
